# Generated by Django 3.0.9 on 2020-08-19 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummyoffer',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dummyoffer',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dummyoffer',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dummyproduct',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dummyproduct',
            name='photo_url',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='dummyproduct',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dummyproduct',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_reported',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
