# Generated by Django 3.0.9 on 2020-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20200819_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyoffer',
            name='dummy',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
