# Generated by Django 3.0.9 on 2020-08-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_remove_dummyoffer_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyoffer',
            name='discount',
        ),
    ]
