# Generated by Django 3.0.9 on 2020-08-19 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0009_delete_dummyoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField(null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_set', to=settings.AUTH_USER_MODEL)),
                ('report', models.ManyToManyField(to='report.Report')),
                ('subscriber', models.ManyToManyField(related_name='subscribed_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
