# Generated by Django 3.0.9 on 2020-08-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20200819_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to='report_images'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
