# Generated by Django 3.0.9 on 2020-09-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20200825_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='tag',
            field=models.ManyToManyField(to='report.Tag'),
        ),
    ]
