# Generated by Django 3.0.9 on 2020-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20200901_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='importance',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='urgency',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], null=True),
        ),
    ]
