# Generated by Django 3.0.9 on 2020-09-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20200902_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='subscriber',
        ),
    ]
