# Generated by Django 3.0.9 on 2020-09-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_auto_20200912_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='taker_notes',
            field=models.TextField(null=True),
        ),
    ]
