# Generated by Django 3.0.9 on 2020-09-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_report_taker_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='taker_note',
            new_name='progress_note',
        ),
    ]
