# Generated by Django 3.0.9 on 2020-09-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_auto_20200913_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='progress_note',
        ),
    ]
