# Generated by Django 3.0.9 on 2020-09-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_remove_report_progress_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='progress_note',
            field=models.TextField(null=True),
        ),
    ]
