# Generated by Django 3.0.9 on 2020-09-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_report_progress_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='progress_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
