# Generated by Django 3.0.9 on 2020-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_auto_20200913_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
