# Generated by Django 3.0.9 on 2020-10-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0027_collaboration_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummyproduct',
        ),
    ]
