# Generated by Django 3.0.9 on 2020-10-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_delete_dummyproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images'),
        ),
    ]
