# Generated by Django 3.0.9 on 2020-10-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0029_auto_20201020_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images'),
        ),
    ]
