# Generated by Django 3.0.9 on 2020-09-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_remove_tag_subscriber'),
        ('user', '0002_auto_20200819_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.ManyToManyField(related_name='subscriber_set', to='report.Tag'),
        ),
    ]
