# Generated by Django 3.0.9 on 2020-09-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200913_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Inactive'), (1, 'Active')], default=1, null=True),
        ),
    ]
