# Generated by Django 3.0.9 on 2020-09-16 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_auto_20200915_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_set', to='user.Unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
