# Generated by Django 3.0.9 on 2020-09-16 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0012_auto_20200916_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unit',
        ),
        migrations.AlterField(
            model_name='unit',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
