# Generated by Django 3.0.9 on 2020-09-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200916_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_set', to='user.Unit'),
        ),
    ]
