# Generated by Django 3.0.9 on 2020-09-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profile_member_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='member_of',
        ),
    ]
