# Generated by Django 3.0.9 on 2020-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20201002_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Create A Report'), (2, 'View Reports'), (3, 'Create A Tag'), (4, 'Take A Report'), (5, 'View Profile Info'), (6, 'Modify Organization'), (7, 'Modify Authorization')], null=True),
        ),
    ]
