# Generated by Django 3.0.9 on 2020-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20201002_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Create A Report'), (2, 'View Reports'), (3, 'Create A Tag'), (4, 'Take A Report'), (5, 'View Profile Info'), (6, 'Manage Organization'), (7, 'Manage Authorization')], null=True),
        ),
    ]
