# Generated by Django 3.0.9 on 2020-10-17 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_pointhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
