# Generated by Django 3.0.9 on 2020-10-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20201017_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='feature',
            field=models.IntegerField(choices=[(1, 'Create A Report'), (2, 'View Reports'), (3, 'Create A Tag'), (4, 'Take A Report'), (5, 'View Profile Info'), (6, 'Manage Organization'), (7, 'Manage Authorization'), (8, 'Manage Points'), (9, 'Collaborate On A Report')], null=True),
        ),
    ]
